### ISSUE TITLE
'/money stats' output is wrong

### ISSUE THREAD

**Issue by Folas1337** [LlmDl/iConomyUnlocked#4]
When using '/money stats', even after changing the lang.yml file to what was recently suggested on Discord[1] it will not show properly.
[1]
```yaml
  stats:
    header: <green>-----[ <white>iConomy Stats <green>]-----
    total: '<gray>Total Accounts: <white>%s'
    average: '<gray>Average %s: <white>%s'
    accounts: '<gray>Total Accounts: <white>%s'
```

It currently shows like this:
![Image](https://github.com/user-attachments/assets/8ee99b7a-18e2-42c9-8a3e-9de45b2aa604)

I assume the first value should show how much money exists, in total, within iConomyUnlocked but I am not entirely sure.
